# Generated by Django 6.1 on 2026-08-31 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0002_station_memberprofile_is_clerk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['station__name', 'name'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AddField(
            model_name='district',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='congregations.station', verbose_name='station'),
        ),
    ]
