# Generated by Django 6.1 on 2026-08-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0003_alter_district_options_district_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
