# Generated by Django 6.1 on 2026-08-31 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0004_memberprofile_first_name_memberprofile_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='local_church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='congregations.localchurch'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
