# Generated by Django 6.1 on 2026-08-31 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mpesa_receipt_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Paystack Reference'),
        ),
    ]
