# Generated by Django 6.1 on 2026-08-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='receipt PDF'),
        ),
    ]
