# Generated by Django 6.1 on 2026-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_receipt_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionallocation',
            name='custom_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
