# Generated by Django 6.1 on 2026-09-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transactionallocation_custom_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt_pdf',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
